name: Deploy to k8s

on:
  push:
    branches:
      - main

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest  # Consider using ubuntu-latest for CI/CD

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Create Docker Image
      uses: docker/build-push-action@v3  # Updated to the latest version
      with:
        context: .
        push: true

    - name: Deploy to k8s
      uses: appleboy/kubectl-action@v1.4.0  # Updated to the latest version
      with:
        args: apply -f deployment.yaml
      env:
        KUBECONFIG: ${{ env.KUBECONFIG }}
