name: End to End CI/CD workflow for Java Application with Maven, Sonar, and k8s Integration

on:
  push:
    branches:
      - main

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  SONAR_TOKEN: ${{ secrets.SONAR_TKN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Java JDK setup
      uses: actions/setup-java@v3  # Updated to the latest version
      with:
        java-version: 17

    - name: Maven target
      run: mvn clean install

    - name: Perform analysis on Sonar Qube
      uses: sonarsource/sonarcloud-github-action@v2  # Updated to the latest version
      with:
        sonarcloud.organization: <name of your org>
        sonarcloud.projectKey: <key>
        sonarcloud.projectName: <name>
        sonarcloud.token: ${{ env.SONAR_TKN }}
        sonarcloud.scannerVersion: "4.2.0.1873"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Deploy to k8s
      uses: stefanzweifel/k8s-action@v2.0.0  # Check for newer versions if available
      with:
        args: apply -f kubernetes/
      env:
        KUBECONFIG: ${{ env.KUBECONFIG }}
